import type { NextPage } from "next";
import Head from "next/head";
import { Upload } from "@/components";
import Papa from "papaparse";
import { FileWithPath } from "@mantine/dropzone";
const Home: NextPage = () => {
  const onFileDropHandler = (file: FileWithPath[]) => {
    if (!file[0]) return;
    Papa.parse(file[0], {
      complete: function (results) {
        console.log("Finished:", results);
      },
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Upload onDropHandler={onFileDropHandler} />
      </main>
    </>
  );
};

export default Home;
