import type { NextPage } from "next";
import Head from "next/head";
import { Upload } from "@/components";
import Papa from "papaparse";
import { FileWithPath } from "@mantine/dropzone";
import { useDataFormatter } from "@/hooks";
import { useEffect } from "react";
import { StudentsTable } from "@/components";
import { requiredCols } from "global";
const Home: NextPage = () => {
  const { rowState, format } = useDataFormatter();
  const onFileDropHandler = (file: FileWithPath[]) => {
    if (!file[0]) return;
    Papa.parse(file[0], {
      complete: function (results: any) {
        console.log("Finished:", results);
        format(results.data);
      },
    });
  };

  useEffect(() => {
    console.log(rowState);
  }, [rowState]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Upload onDropHandler={onFileDropHandler} />
        <StudentsTable headers={Object.keys(requiredCols)} data={rowState} />
      </main>
    </>
  );
};

export default Home;
